name: hadooplab

services:
  hadoop-master:
    build:
      context: ./hadoop
    image: hadooplab/hadoop
    container_name: hadoop-master
    restart: unless-stopped
    hostname: hadoop-master
    environment:
      MASTER: "hadoop-master"
    command: ["/usr/local/bin/entrypoint-master.sh"]
    expose:
      - 9870          # HDFS NameNode UI
      - 8088          # YARN ResourceManager UI
      - 19888         # MapReduce JobHistory Server UI
    volumes:
      - global_conf:/volumes/conf
      - hadoop_master_data:/volumes/data
      - hadoop_master_logs:/volumes/logs
    networks: [net]

  hadoop-worker1:
    build:
      context: ./hadoop
    image: hadooplab/hadoop
    container_name: hadoop-worker1
    depends_on:
      hadoop-master:
        condition: service_started
    restart: unless-stopped
    hostname: hadoop-worker1
    environment:
      MASTER: "hadoop-master"
    command: ["/usr/local/bin/entrypoint-worker.sh"]
    expose:
      - 9864          # HDFS DataNode UI
      - 8042          # YARN NodeManager UI
    volumes:
      - global_conf:/volumes/conf
      - hadoop_worker1_data:/volumes/data
      - hadoop_worker1_logs:/volumes/logs
    networks: [net]

  hadoop-worker2:
    build:
      context: ./hadoop
    image: hadooplab/hadoop
    container_name: hadoop-worker2
    depends_on:
      hadoop-master:
        condition: service_started
    restart: unless-stopped
    hostname: hadoop-worker2
    environment:
      MASTER: "hadoop-master"
    command: ["/usr/local/bin/entrypoint-worker.sh"]
    expose:
      - 9864          # HDFS DataNode UI
      - 8042          # YARN NodeManager UI
    volumes:
      - global_conf:/volumes/conf
      - hadoop_worker2_data:/volumes/data
      - hadoop_worker2_logs:/volumes/logs
    networks: [net]

  hadoop-worker3:
    build:
      context: ./hadoop
    image: hadooplab/hadoop
    container_name: hadoop-worker3
    depends_on:
      hadoop-master:
        condition: service_started
    restart: unless-stopped
    hostname: hadoop-worker3
    environment:
      MASTER: "hadoop-master"
    command: ["/usr/local/bin/entrypoint-worker.sh"]
    expose:
      - 9864          # HDFS DataNode UI
      - 8042          # YARN NodeManager UI
    volumes:
      - global_conf:/volumes/conf
      - hadoop_worker3_data:/volumes/data
      - hadoop_worker3_logs:/volumes/logs
    networks: [net]

  hadoop-client:
    build:
      context: ./hadoop
    image: hadooplab/hadoop
    container_name: hadoop-client
    restart: unless-stopped
    hostname: hadoop-client
    environment:
      MASTER: "hadoop-master"
    command: ["/usr/local/bin/entrypoint-client.sh"]
    volumes:
      - global_conf:/volumes/conf
      - hadoop_client_home:/home
      - /bridge:/bridge
    networks: [net]

  nginx:
    build:
      context: ./nginx
    image: hadooplab/nginx
    container_name: nginx
    depends_on: 
      hadoop-master:
        condition: service_started
      hadoop-worker1:
        condition: service_started
      hadoop-worker2:
        condition: service_started
      hadoop-worker3:
        condition: service_started
    restart: unless-stopped
    hostname: nginx
    ports:
      - 9870:9870     # HDFS NameNode UI
      - 8088:8088     # YARN ResourceManager UI
      - 19888:19888   # MapReduce JobHistory Server UI
      - 9864:9864     # HDFS DataNode UI
      - 8042:8042     # YARN NodeManager UI
    networks: [net]

  postgres:
    build:
      context: ./postgres
    image: hadooplab/postgres
    container_name: postgres
    restart: unless-stopped
    hostname: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [net]

volumes:
  global_conf:
  hadoop_master_data:
  hadoop_master_logs:
  hadoop_worker1_data:
  hadoop_worker1_logs:
  hadoop_worker2_data:
  hadoop_worker2_logs:
  hadoop_worker3_data:
  hadoop_worker3_logs:
  hadoop_client_home:
  postgres_data:

networks:
  net:
    driver: bridge
